Event streams webhook samples
TwilioDevEd/api-snippets pull request #1054
Opened 2024-04-12 15:23 UTC by mvazquezrius

2024-06-06 22:15 UTC, sebas1208 commented
Hi @mvazquezrius can you remove the `package.json`, `package-lock.json`, `requirements.txt` and `pom.xml`. The platform will try to load those as code samples. Besides that, the other files will show fine in the docs.

<img width="927" alt="Screenshot 2024-06-06 at 4 56 35 PM" src="https://github.com/TwilioDevEd/api-snippets/assets/5571870/245c8a5b-d6bd-48c1-9478-5f1f331a2183">

*Ignore the zoom toolbar* 😄

2024-06-22 02:58 UTC, bermudezmt requested changes

2024-06-22 02:58 UTC, bermudezmt commented on event-streams/webhooks/python/README.md
> +uvicorn main:app --reload --port 8080
I get an error with this part:
```
Will watch for changes in these directories: ['/Users/mbermudez/repos/api-snippets/event-streams/webhooks-server']
INFO:     Uvicorn running on http://127.0.0.1:8080 (Press CTRL+C to quit)
INFO:     Started reloader process [5973] using WatchFiles
ERROR:    Error loading ASGI app. Could not import module "main".
```

2024-06-22 02:58 UTC, bermudezmt commented on event-streams/webhooks-server/package.json
> +  "main": "main.js",
Does this and line 7 need to be updated since you renamed the JS file?

2024-06-22 03:56 UTC, bermudezmt requested changes

2024-06-22 03:56 UTC, bermudezmt commented on event-streams/webhooks/java/JavaWebhooksClientApplication.java
> +public class JavaWebhooksClientApplication {
Hey, this also needs to be changed now as it's failing after the file rename:

```
INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:41 min
[INFO] Finished at: 2024-06-21T22:00:45-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project java-webhooks-client: Compilation failure
[ERROR] /Users/mbermudez/repos/api-snippets/event-streams/webhooks-server/webhooks-server.10.x.java:[16,8] class JavaWebhooksClientApplication is public, should be declared in a file named JavaWebhooksClientApplication.java
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

2024-07-03 09:59 UTC, bermudezmt commented
A note for Matthew Setter: This is the [commit](https://github.com/TwilioDevEd/api-snippets/pull/1054/commits/13329eb02eb7c5a52468e8cef677f7e500454a09) with the working code samples and relevant README and requirements files.

2024-07-03 10:00 UTC, bermudezmt commented
Thank you again for collaborating with me on this, @sebas1208 and @mvazquezrius . We will be closing the PR on account of our decision to host the content within the Twilio Blog.

2024-07-03 10:00 UTC, closed without merging